# -*- coding: utf-8 -*-
"""Tubes Visualisasi Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mMLAllNrQCl590cLMB1pyyYcReP61K6z
"""

# Commented out IPython magic to ensure Python compatibility.
#Import library

# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px
import seaborn as sns
mpl.style.use('ggplot')

"""# Eksplorasi Data

Membaca dataset
"""

data = pd.read_csv("https://raw.githubusercontent.com/nurhidayahputeri/FinalProject/main/Dataset/saham.csv")

data.info()

"""Mengubah tipe data 'ListingDate' menjadi datetime"""

#Menghapus NA values
df = data.dropna()

df = df.drop(columns=['Shares',
                      'ListingBoard',
                      'MinutesFirstAdded',
                      'MinutesLastUpdated',
                      'HourlyFirstAdded',
                      'HourlyLastUpdated',
                      'DailyFirstAdded',
                      'DailyLastUpdated'])

df = df.sort_values('ListingDate')
df.head()

print('Dimensi data:', df.shape)

df['LastPrice'].plot(kind='hist', alpha=0.35, bins=15, figsize=(14, 8))
plt.title('Distribusi Harga Saham')
plt.xlabel('Harga Saham')
plt.ylabel('Frekuensi')
plt.show();

fig = px.scatter(df, x='ListingDate', y='LastPrice', color='Name',
                 size='MarketCap',
                 labels={'ListingDate':'Tanggal Pencatatan', 'LastPrice':'Harga Terakhir', 'Sector':'Sektor', 'MarketCap':'Kapitalisasi Pasar'},
                 title='Eksplorasi Data Saham')
fig.update_layout(
    title={
        'y':0.9,
        'x':0.5,
        'xanchor': 'center',
        'yanchor': 'top'},
)
fig.show()

fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    )
)

"""DISTRIBUSI HARGA SAHAM

Perbandingan MarketCap dan Sector
"""

fig, ax1 = plt.subplots(figsize=(12, 6))

df.groupby('Sector')['MarketCap'].sum().plot(kind='line', ax=ax1)
ax1.set_title('Perbandingan Kapitalisasi Pasar antar-Sektor')
ax1.set_xlabel('Sektor')
ax1.set_ylabel('Kapitalisasi Pasar')

plt.tight_layout()
plt.show()

correlation = df.corr(numeric_only=True)

# Membuat peta panas korelasi menggunakan Seaborn
plt.figure(figsize=(10, 8))  # Ukuran plot
sns.heatmap(correlation, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Korelasi Antar Variabel')
plt.show()

